language: go

go:
  - 1.7

install:
  - go get golang.org/x/tools/cmd/cover
  # - go get github.com/mattn/goveralls
  - git clone -b multiple-packages https://github.com/haya14busa/goveralls $GOPATH/src/github.com/haya14busa/goveralls
  - cd $GOPATH/src/github.com/haya14busa/goveralls
  - go get -d -v -t ./...
  - go install
  - cd -

script:
  - goveralls -service=travis-ci
